import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { CalendarDays, CarFront, CheckCircle2, Clock3, Crosshair, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Star, Wrench, X, Gauge, Disc3, ClipboardCheck, ChevronRight, Mail, Handshake } from 'lucide-react'
import './styles.css'

const phone='695047124';
const services=[
  ['Neumáticos','Venta y montaje de neumáticos para todo tipo de vehículos.',Disc3,'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=500&q=80'],
  ['Alineación','Mejora la seguridad, el confort y alarga la vida de tus neumáticos.',Crosshair,'https://images.unsplash.com/photo-1632823471565-1ec8c75f9f19?auto=format&fit=crop&w=500&q=80'],
  ['Equilibrado','Equilibrado electrónico para una conducción más segura y sin vibraciones.',Gauge,'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=500&q=80'],
  ['Mecánica rápida','Revisiones, cambios de filtros, baterías y mucho más.',Wrench,'https://images.unsplash.com/photo-1504222490345-c075b6008014?auto=format&fit=crop&w=500&q=80'],
  ['Frenos / Aceite','Sustitución de pastillas y discos, cambio de aceite y mantenimiento esencial.',Disc3,'https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=500&q=80'],
  ['Revisión','Revisión completa para mayor seguridad en tu día a día.',ClipboardCheck,'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?auto=format&fit=crop&w=500&q=80']
] as const;
const nav=['Inicio','Servicios','Sobre nosotros','Reseñas','Contacto'];
function Logo(){return <div className="logo" aria-label="Neumáticos y Servicios JL"><b>J</b><i>L</i><span>NEUMÁTICOS<br/>Y SERVICIOS JL</span></div>}
function App(){const [open,setOpen]=useState(false); const scroll=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};return <>
<header><div className="wrap header"><Logo/><nav>{nav.map((n,i)=><button key={n} onClick={()=>scroll(i===0?'inicio':i===1?'servicios':i===3?'resenas':i===4?'contacto':'nosotros')}>{n}</button>)}</nav><div className="head-actions"><a className="phone-pill" href="tel:912837230"><Phone/>91 283 72 30</a><button className="btn red small" onClick={()=>scroll('contacto')}>Pedir presupuesto <ChevronRight/></button></div><button className="hamburger" onClick={()=>setOpen(!open)} aria-label="Abrir menú">{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-menu">{nav.map((n,i)=><button key={n} onClick={()=>scroll(i===0?'inicio':i===1?'servicios':i===3?'resenas':i===4?'contacto':'nosotros')}>{n}</button>)}</div>}</header>
<main id="inicio"><section className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="wrap hero-content"><p className="eyebrow">TU TALLER DE CONFIANZA EN MADRID</p><h1>Especialistas en<br/>neumáticos y alineación<br/><em>en Madrid</em></h1><p className="lead">Neumáticos, montaje, equilibrado, alineación de dirección y mecánica rápida. Servicio profesional, rápido y de confianza en Fuencarral y toda la zona norte de Madrid.</p><div className="ctas"><button className="btn red" onClick={()=>scroll('contacto')}><CalendarDays/>Pedir presupuesto <ChevronRight/></button><a className="btn outline" href={'tel:'+phone}><Phone/>Llamar ahora</a><a className="btn whatsapp" href={'https://wa.me/34'+phone} target="_blank"><MessageCircle/>WhatsApp</a></div><div className="trust"><div><Star/><strong>4.8/5</strong><span>233 reseñas</span></div><div><Clock3/><span>Atención rápida<br/>y profesional</span></div><div><ShieldCheck/><span>Primeras marcas<br/>y todos los presupuestos</span></div><div className="location"><MapPin/><span>Fuencarral y<br/>zona norte de Madrid</span></div></div></div></section>
<section id="servicios" className="services wrap"><div className="section-head"><div><p className="eyebrow">SERVICIOS</p><h2>Todo lo que tu vehículo necesita</h2></div><p>En Neumáticos y Servicios JL ofrecemos un servicio integral para el cuidado de tu vehículo, con la experiencia y la calidad de un taller especializado.</p><button onClick={()=>scroll('contacto')}>Ver todos los servicios <ChevronRight/></button></div><div className="service-grid">{services.map(([title,copy,Icon,img])=><article className="service" key={title}><img src={img} alt={title}/><div className="icon"><Icon/></div><div><h3>{title}</h3><p>{copy}</p></div><ChevronRight className="next"/></article>)}</div></section>
<section className="brands"><div className="wrap"><div><p className="eyebrow">PRIMERAS MARCAS, TODAS LAS OPCIONES</p><h2>Neumáticos de las mejores marcas<br/>y para todos los presupuestos</h2></div><span>MICHELIN</span><span>Continental</span><span>BRIDGESTONE</span><span>PIRELLI</span><span>GOODYEAR</span><span>DUNLOP</span></div></section>
<section id="resenas" className="lower"><div className="reviews"><div className="wrap review-inner"><div><p className="eyebrow">LO QUE OPINAN NUESTROS CLIENTES</p><strong className="rating">4.8/5 <small>★★★★★</small></strong><p>Basado en 233 reseñas de Google</p></div><blockquote>“<br/>Grandes profesionales, rápidos y honestos. Siempre que necesito neumáticos o una revisión vengo aquí. Totalmente recomendables.”<footer>Cliente local</footer></blockquote></div></div><div id="nosotros" className="why"><div className="wrap"><p className="eyebrow">¿POR QUÉ ELEGIRNOS?</p><h2>¿Por qué elegir Neumáticos y Servicios JL?</h2><div className="why-grid">{[[CheckCircle2,'Atención rápida','Tu tiempo es importante. Servicio ágil y eficaz.'],[Star,'Primeras marcas','Neumáticos de calidad al mejor precio, para todos los presupuestos.'],[Handshake,'Honestidad y confianza','Te asesoramos siempre con transparencia, sin sorpresas.'],[ClipboardCheck,'Presupuesto sin compromiso','Consulta y te ayudamos a elegir la mejor opción.']].map(([I,t,d])=>{const Icon=I as typeof CheckCircle2;return <div key={t as string}><Icon/><section><h3>{t as string}</h3><p>{d as string}</p></section></div>})}</div></div></div></section>
</main><footer id="contacto"><div className="wrap footer"><div><Logo/><p>Tu taller de confianza en Fuencarral, Madrid.</p></div><div><MapPin/><p>Calle Ntra. Señora de Valverde 175<br/>28034 Madrid (Fuencarral)</p><a className="directions" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Calle+Ntra.+Se%C3%B1ora+de+Valverde+175+Madrid">Cómo llegar <ChevronRight/></a></div><div><Phone/><p>695 04 71 24<br/>615 18 85 42<br/>91 283 72 30</p><Mail/><a href="mailto:neumaticosyserviciosjl@gmail.com">neumaticosyserviciosjl@gmail.com</a></div><div><Clock3/><p>Lunes a Viernes<br/>09:00 - 14:00<br/>16:00 - 18:00</p></div><a className="map" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Calle+Ntra.+Se%C3%B1ora+de+Valverde+175+Madrid"><MapPin/>Calle Ntra. Señora<br/>de Valverde 175</a></div></footer></>}
createRoot(document.getElementById('root')!).render(<App/>);
